<?php
$data = array (
  0 => 
  array (
    'goods_id' => '883',
    'cat_id' => '1333',
    'goods_name' => '杜蕾斯旗舰店震动棒女用振动自慰器抽插高潮夫妻情趣用品另类玩具 品牌保障 G点强震刺激 安心防水 多频速',
    'market_price' => '<em>¥</em>238.79',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '199.00',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>199.00',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'http://kjwbb.oss-cn-hangzhou.aliyuncs.com/images/201703/thumb_img/0_thumb_G_1490224092113.jpg',
    'goods_img' => 'http://kjwbb.oss-cn-hangzhou.aliyuncs.com/images/201703/goods_img/0_G_1490224092963.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => '杜蕾斯旗舰店震动棒女用振动自慰器抽插高潮夫妻情趣用品另类玩具 品牌保障 G点强震刺激 安心防水 多频速',
    'url' => 'goods.php?id=883',
  ),
  1 => 
  array (
    'goods_id' => '882',
    'cat_id' => '1330',
    'goods_name' => '杜蕾斯旗舰店 芦荟按摩油人体润滑剂男用 润滑油夫妻房事用品 按摩调情 舒适润滑 情趣之选',
    'market_price' => '<em>¥</em>82.80',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '69.00',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>69.00',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'http://kjwbb.oss-cn-hangzhou.aliyuncs.com/images/201703/thumb_img/0_thumb_G_1490224058799.jpg',
    'goods_img' => 'http://kjwbb.oss-cn-hangzhou.aliyuncs.com/images/201703/goods_img/0_G_1490224058751.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => '杜蕾斯旗舰店 芦荟按摩油人体润滑剂男用 润滑油夫妻房事用品 按摩调情 舒适润滑 情趣之选',
    'url' => 'goods.php?id=882',
  ),
  2 => 
  array (
    'goods_id' => '881',
    'cat_id' => '1333',
    'goods_name' => '宫廷 女夏秋情趣内衣极度性感睡衣诱惑蕾丝肚兜短裙大码结婚礼物 漂亮盒装 蕾丝系带挂脖 弹力半透 肚兜+三角裤',
    'market_price' => '<em>¥</em>42.00',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '35.00',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>35.00',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'http://kjwbb.oss-cn-hangzhou.aliyuncs.com/images/201703/thumb_img/0_thumb_G_1490224029400.jpg',
    'goods_img' => 'http://kjwbb.oss-cn-hangzhou.aliyuncs.com/images/201703/goods_img/0_G_1490224029420.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => '宫廷 女夏秋情趣内衣极度性感睡衣诱惑蕾丝肚兜短裙大码结婚礼物 漂亮盒装 蕾丝系带挂脖 弹力半透 肚兜+三角裤',
    'url' => 'goods.php?id=881',
  ),
  3 => 
  array (
    'goods_id' => '880',
    'cat_id' => '1333',
    'goods_name' => '赤芯情趣内衣蕾丝挂脖极度性感肚兜睡衣诱惑透明系带新结婚庆礼物 精美包装 个性图案 半透诱惑 复古风格 实惠套装',
    'market_price' => '<em>¥</em>34.08',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '28.40',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>28.40',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'http://kjwbb.oss-cn-hangzhou.aliyuncs.com/images/201703/thumb_img/0_thumb_G_1490224002017.jpg',
    'goods_img' => 'http://kjwbb.oss-cn-hangzhou.aliyuncs.com/images/201703/goods_img/0_G_1490224002701.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => '赤芯情趣内衣蕾丝挂脖极度性感肚兜睡衣诱惑透明系带新结婚庆礼物 精美包装 个性图案 半透诱惑 复古风格 实惠套装',
    'url' => 'goods.php?id=880',
  ),
  4 => 
  array (
    'goods_id' => '879',
    'cat_id' => '1333',
    'goods_name' => '赤芯 黑色蕾丝吊带丝袜 吊袜带极度性感长筒网袜诱惑激情情趣内衣 面纱+上衣+手套+内裤+蕾丝吊带袜',
    'market_price' => '<em>¥</em>36.48',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '30.40',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>30.40',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'http://kjwbb.oss-cn-hangzhou.aliyuncs.com/images/201703/thumb_img/0_thumb_G_1490223973773.jpg',
    'goods_img' => 'http://kjwbb.oss-cn-hangzhou.aliyuncs.com/images/201703/goods_img/0_G_1490223973354.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => '赤芯 黑色蕾丝吊带丝袜 吊袜带极度性感长筒网袜诱惑激情情趣内衣 面纱+上衣+手套+内裤+蕾丝吊带袜',
    'url' => 'goods.php?id=879',
  ),
  5 => 
  array (
    'goods_id' => '878',
    'cat_id' => '1333',
    'goods_name' => '杜蕾斯旗舰店私处紧致阴道哑铃女用产后恢复缩阴球成人情趣性用品 健康紧致 专属app 配套训练 官方正品',
    'market_price' => '<em>¥</em>298.80',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '249.00',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>249.00',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'http://kjwbb.oss-cn-hangzhou.aliyuncs.com/images/201703/thumb_img/0_thumb_G_1490223936757.jpg',
    'goods_img' => 'http://kjwbb.oss-cn-hangzhou.aliyuncs.com/images/201703/goods_img/0_G_1490223936115.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => '杜蕾斯旗舰店私处紧致阴道哑铃女用产后恢复缩阴球成人情趣性用品 健康紧致 专属app 配套训练 官方正品',
    'url' => 'goods.php?id=878',
  ),
  6 => 
  array (
    'goods_id' => '877',
    'cat_id' => '1328',
    'goods_name' => '杜蕾斯官方旗舰店 AiR空气套量贩装安全套 超薄装避孕套男用正品 量贩钜惠 正品保障 薄柔滑贴净',
    'market_price' => '<em>¥</em>298.80',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '249.00',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>249.00',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'http://kjwbb.oss-cn-hangzhou.aliyuncs.com/images/201703/thumb_img/0_thumb_G_1490223899923.jpg',
    'goods_img' => 'http://kjwbb.oss-cn-hangzhou.aliyuncs.com/images/201703/goods_img/0_G_1490223899629.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => '杜蕾斯官方旗舰店 AiR空气套量贩装安全套 超薄装避孕套男用正品 量贩钜惠 正品保障 薄柔滑贴净',
    'url' => 'goods.php?id=877',
  ),
  7 => 
  array (
    'goods_id' => '876',
    'cat_id' => '1328',
    'goods_name' => '杜蕾斯官方旗舰店 凸点螺纹装12只避孕套大号 情趣型安全套套byt 凸点螺纹刺激 有型易戴 官方品质保障',
    'market_price' => '<em>¥</em>70.80',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '59.00',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>59.00',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'http://kjwbb.oss-cn-hangzhou.aliyuncs.com/images/201703/thumb_img/0_thumb_G_1490223850447.jpg',
    'goods_img' => 'http://kjwbb.oss-cn-hangzhou.aliyuncs.com/images/201703/goods_img/0_G_1490223850303.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => '杜蕾斯官方旗舰店 凸点螺纹装12只避孕套大号 情趣型安全套套byt 凸点螺纹刺激 有型易戴 官方品质保障',
    'url' => 'goods.php?id=876',
  ),
  8 => 
  array (
    'goods_id' => '875',
    'cat_id' => '1328',
    'goods_name' => '杜蕾斯官方旗舰店 持久装男用延时避孕套3只成人情趣安全套套正品 苯佐卡因延时 放心可靠 持久快感',
    'market_price' => '<em>¥</em>90.00',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '75.00',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>75.00',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'http://kjwbb.oss-cn-hangzhou.aliyuncs.com/images/201703/thumb_img/0_thumb_G_1490223817949.jpg',
    'goods_img' => 'http://kjwbb.oss-cn-hangzhou.aliyuncs.com/images/201703/goods_img/0_G_1490223817794.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => '杜蕾斯官方旗舰店 持久装男用延时避孕套3只成人情趣安全套套正品 苯佐卡因延时 放心可靠 持久快感',
    'url' => 'goods.php?id=875',
  ),
);
?>